server:
  port: 8080
spring:
  datasource:
    password: root
    username: root
#    driver-class-name: com.mysql.cj.jdbc.Driver  # 这里已经可以自动注入了
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
